### ISSUE TITLE
raspberry pi 3

### ISSUE THREAD

**Issue by erikversonnen** [othermod/PSPi-1000-Version-4#12]
what modification is done to get it working on RPi 3?
does it work with retropie 4.5?

**Comment by bademux** [comment]
o maybe it is better to use Raspberry Pi CM (Compute Module)? (latest 3+ as for now)
What do you think?
When we can order next PCB (v4.2? )
 @othermod

**Comment by othermod** [comment]
@erikversonnen 
The PRi 3 can be attached using the same header and camera connector. Lots of soldering is required. I think a couple people have managed it. If you want to check out my Discord, somewhere there might have some tips. Not sure about retropie 4.5 support yet. I'll have to look into it.

@bademux 
The RPi 3A is more appealing to me because it has wifi/BT onboard. Might go the CM route if I am able to find the time to design it. I can't give a timeline on the next board. It's on hold for a bit while I finish my YouTube recording setup. It's also very possible that I won't be selling the boards. It all depends on whether I can get them manufactured at a reasonable price.

**Comment by bademux** [comment]
Upd with links
Indeed RPi 3A+ seems to be good choice, but CM module will allow to simplify wiring here example:
https://hackaday.io/project/94791-retro-cm3-a-powerful-retropie-handled-game-consol
https://github.com/Dean-Chu/Retro-CM3
Hope it will be possible to use something like https://jlcpcb.com/smt-assembly or ready-to-use daughterboards that will be soldered to mainboard.

Let me thank you for your project: 4.3" LCD + PSP case is really great combo!

**Comment by erikversonnen** [comment]
I've connected a rpi3 a+ and display is working, buttons do not work, i've connected the CSI connector, and messured if the connection is ok for buttons,power,... 
between sda en scl i messured 3,9 k ohm, if i run i2cdetect -y 0 i only see something on address 8x60 uu. Any Idea what the problem could be? I use the latest version of retropie

**Comment by othermod** [comment]
@erikversonnen  You'll also have to change the overlay so that it uses the correct pins on the Pi3. I can't remember the exact pins, 44 and 45 seems right to me. I'll have to check.

**Comment by othermod** [comment]
Yeah I think 44 and 45 are correct
https://github.com/raspberrypi/firmware/blob/master/extra/dt-blob.dts
pin@p44 { function = "input";   termination = "pull_up";    }; // I2C 0 SDA
pin@p45 { function = "input";   termination = "pull_up";    }; // I2C 0 SCL

Try replacing this in config.txt 
dtoverlay=i2c0-bcm2708,pins_28_29
with this
dtoverlay=i2c0-bcm2708,pins_44_45

**Comment by erikversonnen** [comment]
I can conform changing the config file works, 

Thanks for the help
Much appreciated
